Added gradual change detection
Trelent/Trelent-VSCode-Extension pull request #34
Opened 2023-04-26 20:20 UTC by calum-bird

2023-04-27 03:48 UTC, calum-bird commented
Alright the TLDR here is I've got no idea how the changes I made are causing this test to fail. Seems a bit peculiar.

2023-04-28 18:37 UTC, Coolroo approved these changes
LGTM!

2023-04-28 18:38 UTC, Coolroo requested changes

2023-04-28 18:38 UTC, Coolroo commented on src/autodoc/changeDetection.ts
> +          returnObj.all.push(functionPair["old"]);
Are we persisting old functions? This probably shouldn't happen

2023-04-28 19:44 UTC, Coolroo approved these changes
LGTM!

2023-04-29 21:19 UTC, merged